blank_issues_enabled: false
contact_links:
  - name: Droptop Four Support, Bug report and Feature Requests
    url: https://droptopfour.com/discord
    about: On the Droptop Four Discord server you can get support, report new bugs and make suggestions on features you'd like to use on Droptop.
