name: Badges

on:
  workflow_dispatch

jobs:
  update-badges:
    name: Update Badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download cloc
        run: sudo apt-get update -y && sudo apt-get install -y cloc
      - name: Get the Numbers
        run: |
          echo "CODE_LINES=$(   ./.github/scripts/cloc.sh --loc)" >> $GITHUB_ENV
      - name: Create Lines-of-Code-Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 0082c3b7bfd24146abe41c5ff336164f
          filename: ${{ secrets.REPO_NAME }}.json
          label: Lines of Code
          message: ${{ env.CODE_LINES }}
          color: green
